### ISSUE TITLE
Auto Suggest demo is broken

### ISSUE THREAD

**Issue by GiantCrocodile** [eclipse-rap/org.eclipse.rap.website#3]
Hello,

when you put in a country and a city, e. g. Germany and Bremen, the application under https://rap.eclipsesource.com/demo/release/rapdemo/#drop-down is breaking/having a server issue:

![Screenshot 2024-03-10 192425](https://github.com/eclipse-rap/org.eclipse.rap.website/assets/6271057/5197b0ba-a4bf-48a9-a6f4-1495bdd25709)

![Screenshot 2024-03-10 192408](https://github.com/eclipse-rap/org.eclipse.rap.website/assets/6271057/2268702a-eff0-4bcd-a3fe-0196fe858c70)

Looks like HTTPS only is supported so the mixed content is failing. Happens in Firefox and Edge.

Best Regards,

**Comment by mknauer** [comment]
Thank you for reporting the issue.

It belongs to the [RAP Runtime project](https://github.com/eclipse-rap/org.eclipse.rap). I have created a copy of the issue there (https://github.com/eclipse-rap/org.eclipse.rap/issues/177), and will close this one here.
